//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annee
    {
        public Annee()
        {
            this.Periodes = new HashSet<Periode>();
            this.Bonuses = new HashSet<Bonus>();
        }
    
        public int AnneeID { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int CompagnieID { get; set; }
        public int StatutAnneeID { get; set; }
    
        public virtual Compagnie Compagnie { get; set; }
        public virtual StatutAnnee StatutAnnee { get; set; }
        public virtual ICollection<Periode> Periodes { get; set; }
        public virtual ICollection<Bonus> Bonuses { get; set; }
    }
}
