//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppMenuEntities : DbContext
    {
        public AppMenuEntities()
            : base("name=AppMenuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuRole> MenuRoles { get; set; }
        public DbSet<SubMenu> SubMenus { get; set; }
        public DbSet<SubMenuLink> SubMenuLinks { get; set; }
        public DbSet<SubMenuRole> SubMenuRoles { get; set; }
        public DbSet<SubMenuLinkRole> SubMenuLinkRoles { get; set; }
    }
}
