//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cessation
    {
        public Cessation()
        {
            this.CessationPrelevements = new HashSet<CessationPrelevement>();
        }
    
        public System.DateTime DateCessation { get; set; }
        public decimal Salaire { get; set; }
        public decimal HeureSup { get; set; }
        public decimal Pret { get; set; }
        public decimal BonusAnnuel { get; set; }
        public decimal IndemniteConge { get; set; }
        public decimal IndemniteDepart { get; set; }
        public decimal Avance { get; set; }
        public decimal Retenue { get; set; }
        public decimal Prime { get; set; }
        public long EmployeID { get; set; }
        public decimal Prelevement { get; set; }
        public decimal PrelevementHeureSup { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int TypeCessationID { get; set; }
        public int TypeSalaireID { get; set; }
        public long CessationID { get; set; }
        public decimal TauxConversion { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual TypeCessation TypeCessation { get; set; }
        public virtual TypeSalaire TypeSalaire { get; set; }
        public virtual ICollection<CessationPrelevement> CessationPrelevements { get; set; }
    }
}
