//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compagnie
    {
        public Compagnie()
        {
            this.Annees = new HashSet<Annee>();
            this.CompagnieMonnaies = new HashSet<CompagnieMonnaie>();
            this.CompagnieTypeEmployes = new HashSet<CompagnieTypeEmploye>();
            this.CompagnieTypePaiements = new HashSet<CompagnieTypePaiement>();
            this.Departements = new HashSet<Departement>();
            this.Postes = new HashSet<Poste>();
            this.CompagniePrelevements = new HashSet<CompagniePrelevement>();
            this.CompagnieJourChomes = new HashSet<CompagnieJourChome>();
            this.LocationLogiciels = new HashSet<LocationLogiciel>();
            this.CompagnieTypeConges = new HashSet<CompagnieTypeConge>();
            this.CompagnieContacts = new HashSet<CompagnieContact>();
            this.Banques = new HashSet<Banque>();
            this.TypePeriodes = new HashSet<TypePeriode>();
            this.TypePrets = new HashSet<TypePret>();
        }
    
        public int CompagnieID { get; set; }
        public string Nom { get; set; }
        public string Nif { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public Nullable<int> HoldingID { get; set; }
        public int NumeroEmployeSuivant { get; set; }
        public decimal MensualiteLogiciel { get; set; }
        public System.DateTime ExpirationLogiciel { get; set; }
        public int MaximumEmploye { get; set; }
        public Nullable<int> MonnaieID { get; set; }
    
        public virtual ICollection<Annee> Annees { get; set; }
        public virtual ICollection<CompagnieMonnaie> CompagnieMonnaies { get; set; }
        public virtual ICollection<CompagnieTypeEmploye> CompagnieTypeEmployes { get; set; }
        public virtual ICollection<CompagnieTypePaiement> CompagnieTypePaiements { get; set; }
        public virtual Holding Holding { get; set; }
        public virtual ICollection<Departement> Departements { get; set; }
        public virtual ICollection<Poste> Postes { get; set; }
        public virtual ICollection<CompagniePrelevement> CompagniePrelevements { get; set; }
        public virtual ICollection<CompagnieJourChome> CompagnieJourChomes { get; set; }
        public virtual ICollection<LocationLogiciel> LocationLogiciels { get; set; }
        public virtual ICollection<CompagnieTypeConge> CompagnieTypeConges { get; set; }
        public virtual ICollection<CompagnieContact> CompagnieContacts { get; set; }
        public virtual Monnaie Monnaie { get; set; }
        public virtual ICollection<Banque> Banques { get; set; }
        public virtual ICollection<TypePeriode> TypePeriodes { get; set; }
        public virtual ICollection<TypePret> TypePrets { get; set; }
    }
}
