//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conge
    {
        public Conge()
        {
            this.CongeDetails = new HashSet<CongeDetail>();
        }
    
        public Nullable<decimal> JourParAnnee { get; set; }
        public Nullable<decimal> JourBalance { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public long EmployeID { get; set; }
        public int TypeCongeID { get; set; }
        public bool AccumulableParAnnee { get; set; }
        public bool IncrementableParMois { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual TypeConge TypeConge { get; set; }
        public virtual ICollection<CongeDetail> CongeDetails { get; set; }
    }
}
