//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public Departement()
        {
            this.Employes = new HashSet<Employe>();
            this.Mouvements = new HashSet<Mouvement>();
            this.Departement1 = new HashSet<Departement>();
        }
    
        public int DepartementID { get; set; }
        public Nullable<int> DepartementParentID { get; set; }
        public string Nom { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int CompagnieID { get; set; }
    
        public virtual Compagnie Compagnie { get; set; }
        public virtual ICollection<Employe> Employes { get; set; }
        public virtual ICollection<Mouvement> Mouvements { get; set; }
        public virtual ICollection<Departement> Departement1 { get; set; }
        public virtual Departement Departement2 { get; set; }
    }
}
