//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.Cessations = new HashSet<Cessation>();
            this.Conges = new HashSet<Conge>();
            this.EmployePrelevements = new HashSet<EmployePrelevement>();
            this.HeureSups = new HashSet<HeureSup>();
            this.Mouvements = new HashSet<Mouvement>();
            this.Presences = new HashSet<Presence>();
            this.EmployeSalaires = new HashSet<EmployeSalaire>();
        }
    
        public long EmployeID { get; set; }
        public string Nom { get; set; }
        public string Nif { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string Sexe { get; set; }
        public string AdresseRue1 { get; set; }
        public string AdresseRue2 { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Extension { get; set; }
        public string Email { get; set; }
        public string UrgenceNom { get; set; }
        public string UrgencePhone { get; set; }
        public System.DateTime DateEmbauche { get; set; }
        public Nullable<System.DateTime> DateFinEmbauche { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int NumeroEmploye { get; set; }
        public int DepartementID { get; set; }
        public int StatutEmployeID { get; set; }
        public int StatutMatrimonialID { get; set; }
        public int CompagnieID { get; set; }
        public int TypeEmployeID { get; set; }
        public Nullable<int> PosteID { get; set; }
        public string AdresseVille { get; set; }
        public string Cin { get; set; }
    
        public virtual ICollection<Cessation> Cessations { get; set; }
        public virtual CompagnieTypeEmploye CompagnieTypeEmploye { get; set; }
        public virtual ICollection<Conge> Conges { get; set; }
        public virtual Departement Departement { get; set; }
        public virtual Poste Poste { get; set; }
        public virtual StatutEmploye StatutEmploye { get; set; }
        public virtual StatutMatrimonial StatutMatrimonial { get; set; }
        public virtual ICollection<EmployePrelevement> EmployePrelevements { get; set; }
        public virtual ICollection<HeureSup> HeureSups { get; set; }
        public virtual ICollection<Mouvement> Mouvements { get; set; }
        public virtual ICollection<Presence> Presences { get; set; }
        public virtual EmployePhoto EmployePhoto { get; set; }
        public virtual ICollection<EmployeSalaire> EmployeSalaires { get; set; }
    }
}
