//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holding
    {
        public Holding()
        {
            this.Compagnies = new HashSet<Compagnie>();
        }
    
        public int HoldingID { get; set; }
        public string Nom { get; set; }
        public string Nif { get; set; }
        public bool RapportConsolide { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        public virtual ICollection<Compagnie> Compagnies { get; set; }
    }
}
