//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationLogiciel
    {
        public int LocationLogicielID { get; set; }
        public decimal LocationPaiement { get; set; }
        public System.DateTime ExpirationLogiciel { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int CompagnieID { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
    
        public virtual Compagnie Compagnie { get; set; }
    }
}
