//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.SubMenus = new HashSet<SubMenu>();
            this.MenuRoles = new HashSet<MenuRole>();
        }
    
        public int MenuID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual ICollection<SubMenu> SubMenus { get; set; }
        public virtual ICollection<MenuRole> MenuRoles { get; set; }
    }
}
