//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monnaie
    {
        public Monnaie()
        {
            this.Compagnies = new HashSet<Compagnie>();
            this.CompagnieMonnaies = new HashSet<CompagnieMonnaie>();
            this.EmployeSalaires = new HashSet<EmployeSalaire>();
            this.TauxMonnaiePeriodes = new HashSet<TauxMonnaiePeriode>();
            this.MouvementSalaires = new HashSet<MouvementSalaire>();
        }
    
        public int MonnaieID { get; set; }
        public string Nom { get; set; }
        public string Abreviation { get; set; }
        public string Symbol { get; set; }
        public bool Locale { get; set; }
    
        public virtual ICollection<Compagnie> Compagnies { get; set; }
        public virtual ICollection<CompagnieMonnaie> CompagnieMonnaies { get; set; }
        public virtual ICollection<EmployeSalaire> EmployeSalaires { get; set; }
        public virtual ICollection<TauxMonnaiePeriode> TauxMonnaiePeriodes { get; set; }
        public virtual ICollection<MouvementSalaire> MouvementSalaires { get; set; }
    }
}
