//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public Mouvement()
        {
            this.MouvementSalaires = new HashSet<MouvementSalaire>();
        }
    
        public long MouvementID { get; set; }
        public Nullable<System.DateTime> DateMouvement { get; set; }
        public long EmployeID { get; set; }
        public int TypeMouvementID { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int DepartementID { get; set; }
        public int PosteID { get; set; }
    
        public virtual Departement Departement { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Poste Poste { get; set; }
        public virtual TypeMouvement TypeMouvement { get; set; }
        public virtual ICollection<MouvementSalaire> MouvementSalaires { get; set; }
    }
}
