//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MouvementSalaire
    {
        public int MouvementSalaireID { get; set; }
        public long MouvementID { get; set; }
        public decimal Salaire { get; set; }
        public int MonnaieID { get; set; }
        public int TypeSalaireID { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
    
        public virtual Monnaie Monnaie { get; set; }
        public virtual Mouvement Mouvement { get; set; }
        public virtual TypeSalaire TypeSalaire { get; set; }
    }
}
