//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paye
    {
        public Paye()
        {
            this.PayePrelevements = new HashSet<PayePrelevement>();
        }
    
        public Nullable<decimal> salaire { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<decimal> Retenue { get; set; }
        public Nullable<decimal> TauxConversion { get; set; }
        public Nullable<decimal> Pret { get; set; }
        public Nullable<decimal> Prime { get; set; }
        public Nullable<decimal> Prelevement { get; set; }
        public Nullable<decimal> HeureSup { get; set; }
        public Nullable<decimal> PrelevementHeureSup { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int PeriodeID { get; set; }
        public long PayeID { get; set; }
        public decimal Ajustement { get; set; }
        public long EmployeID { get; set; }
        public int TypeSalaireID { get; set; }
    
        public virtual EmployeSalaire EmployeSalaire { get; set; }
        public virtual Periode Periode { get; set; }
        public virtual ICollection<PayePrelevement> PayePrelevements { get; set; }
    }
}
