//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Annee> Annees { get; set; }
        public DbSet<Avance> Avances { get; set; }
        public DbSet<Banque> Banques { get; set; }
        public DbSet<Bonus> Bonuses { get; set; }
        public DbSet<BonusPrelevement> BonusPrelevements { get; set; }
        public DbSet<Cessation> Cessations { get; set; }
        public DbSet<CessationPrelevement> CessationPrelevements { get; set; }
        public DbSet<Compagnie> Compagnies { get; set; }
        public DbSet<CompagnieContact> CompagnieContacts { get; set; }
        public DbSet<CompagnieJourChome> CompagnieJourChomes { get; set; }
        public DbSet<CompagnieMonnaie> CompagnieMonnaies { get; set; }
        public DbSet<CompagniePrelevement> CompagniePrelevements { get; set; }
        public DbSet<CompagnieTypeConge> CompagnieTypeConges { get; set; }
        public DbSet<CompagnieTypeEmploye> CompagnieTypeEmployes { get; set; }
        public DbSet<CompagnieTypePaiement> CompagnieTypePaiements { get; set; }
        public DbSet<CompagnieTypeSalaire> CompagnieTypeSalaires { get; set; }
        public DbSet<Conge> Conges { get; set; }
        public DbSet<CongeDetail> CongeDetails { get; set; }
        public DbSet<Departement> Departements { get; set; }
        public DbSet<Employe> Employes { get; set; }
        public DbSet<EmployePhoto> EmployePhotoes { get; set; }
        public DbSet<EmployePrelevement> EmployePrelevements { get; set; }
        public DbSet<EmployeSalaire> EmployeSalaires { get; set; }
        public DbSet<HeureSup> HeureSups { get; set; }
        public DbSet<Holding> Holdings { get; set; }
        public DbSet<JourChomeReference> JourChomeReferences { get; set; }
        public DbSet<LocationLogiciel> LocationLogiciels { get; set; }
        public DbSet<Monnaie> Monnaies { get; set; }
        public DbSet<Mouvement> Mouvements { get; set; }
        public DbSet<MouvementSalaire> MouvementSalaires { get; set; }
        public DbSet<NaturePrelevement> NaturePrelevements { get; set; }
        public DbSet<Paye> Payes { get; set; }
        public DbSet<PayeAjustement> PayeAjustements { get; set; }
        public DbSet<PayePrelevement> PayePrelevements { get; set; }
        public DbSet<Periode> Periodes { get; set; }
        public DbSet<Poste> Postes { get; set; }
        public DbSet<Prelevement> Prelevements { get; set; }
        public DbSet<PrelevementApplication> PrelevementApplications { get; set; }
        public DbSet<PrelevementDetail> PrelevementDetails { get; set; }
        public DbSet<Presence> Presences { get; set; }
        public DbSet<Pret> Prets { get; set; }
        public DbSet<PretPeriode> PretPeriodes { get; set; }
        public DbSet<PretRemboursement> PretRemboursements { get; set; }
        public DbSet<StatutAnnee> StatutAnnees { get; set; }
        public DbSet<StatutEmploye> StatutEmployes { get; set; }
        public DbSet<StatutMatrimonial> StatutMatrimonials { get; set; }
        public DbSet<StatutPeriode> StatutPeriodes { get; set; }
        public DbSet<TauxMonnaiePeriode> TauxMonnaiePeriodes { get; set; }
        public DbSet<TypeAjustement> TypeAjustements { get; set; }
        public DbSet<TypeCessation> TypeCessations { get; set; }
        public DbSet<TypeConge> TypeConges { get; set; }
        public DbSet<TypeEmploye> TypeEmployes { get; set; }
        public DbSet<TypeMouvement> TypeMouvements { get; set; }
        public DbSet<TypePaiement> TypePaiements { get; set; }
        public DbSet<TypePeriode> TypePeriodes { get; set; }
        public DbSet<TypePrelevement> TypePrelevements { get; set; }
        public DbSet<TypePret> TypePrets { get; set; }
        public DbSet<TypeSalaire> TypeSalaires { get; set; }
    
        public virtual int GetEmployeInternalNumber(Nullable<int> companyID, ObjectParameter numeroEmploye)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetEmployeInternalNumber", companyIDParameter, numeroEmploye);
        }
    }
}
