//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periode
    {
        public Periode()
        {
            this.Payes = new HashSet<Paye>();
            this.PayeAjustements = new HashSet<PayeAjustement>();
            this.PretRemboursements = new HashSet<PretRemboursement>();
            this.TauxMonnaiePeriodes = new HashSet<TauxMonnaiePeriode>();
        }
    
        public int PeriodeID { get; set; }
        public string Nom { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public int AnneeID { get; set; }
        public int StatutPeriodeID { get; set; }
        public int TypePeriodeID { get; set; }
    
        public virtual Annee Annee { get; set; }
        public virtual ICollection<Paye> Payes { get; set; }
        public virtual ICollection<PayeAjustement> PayeAjustements { get; set; }
        public virtual StatutPeriode StatutPeriode { get; set; }
        public virtual TypePeriode TypePeriode { get; set; }
        public virtual ICollection<PretRemboursement> PretRemboursements { get; set; }
        public virtual ICollection<TauxMonnaiePeriode> TauxMonnaiePeriodes { get; set; }
    }
}
