//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrelevementApplication
    {
        public PrelevementApplication()
        {
            this.Prelevements = new HashSet<Prelevement>();
        }
    
        public int PrelevementApplicationID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Prelevement> Prelevements { get; set; }
    }
}
