//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public long PresenceID { get; set; }
        public System.DateTime DatePresence { get; set; }
        public string ModifiePar { get; set; }
        public decimal HeurePresence { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public long EmployeID { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
