//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pret
    {
        public Pret()
        {
            this.PretPeriodes = new HashSet<PretPeriode>();
            this.PretRemboursements = new HashSet<PretRemboursement>();
        }
    
        public long PretID { get; set; }
        public decimal Montant { get; set; }
        public System.DateTime DatePret { get; set; }
        public decimal Balance { get; set; }
        public string ModifiePar { get; set; }
        public Nullable<System.DateTime> ModifieDate { get; set; }
        public int TypePretID { get; set; }
        public long EmployeID { get; set; }
        public int TypeSalaireID { get; set; }
        public Nullable<int> BanqueID { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual EmployeSalaire EmployeSalaire { get; set; }
        public virtual TypePret TypePret { get; set; }
        public virtual ICollection<PretPeriode> PretPeriodes { get; set; }
        public virtual ICollection<PretRemboursement> PretRemboursements { get; set; }
    }
}
