//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public SubMenu()
        {
            this.SubMenuRoles = new HashSet<SubMenuRole>();
            this.SubMenuLinks = new HashSet<SubMenuLink>();
        }
    
        public int SubMenuID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public int MenuID { get; set; }
        public int OrderNumber { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<SubMenuRole> SubMenuRoles { get; set; }
        public virtual ICollection<SubMenuLink> SubMenuLinks { get; set; }
    }
}
