//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TauxMonnaiePeriode
    {
        public decimal TauxConversion { get; set; }
        public int PeriodeID { get; set; }
        public int MonnaieID { get; set; }
    
        public virtual Monnaie Monnaie { get; set; }
        public virtual Periode Periode { get; set; }
    }
}
