//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeEmploye
    {
        public TypeEmploye()
        {
            this.CompagnieTypeEmployes = new HashSet<CompagnieTypeEmploye>();
        }
    
        public int TypeEmployeID { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CompagnieTypeEmploye> CompagnieTypeEmployes { get; set; }
    }
}
