//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSalaire
    {
        public TypeSalaire()
        {
            this.Cessations = new HashSet<Cessation>();
            this.CompagniePrelevements = new HashSet<CompagniePrelevement>();
            this.CompagnieTypeSalaires = new HashSet<CompagnieTypeSalaire>();
            this.EmployePrelevements = new HashSet<EmployePrelevement>();
            this.EmployeSalaires = new HashSet<EmployeSalaire>();
            this.MouvementSalaires = new HashSet<MouvementSalaire>();
        }
    
        public int TypeSalaireID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Cessation> Cessations { get; set; }
        public virtual ICollection<CompagniePrelevement> CompagniePrelevements { get; set; }
        public virtual ICollection<CompagnieTypeSalaire> CompagnieTypeSalaires { get; set; }
        public virtual ICollection<EmployePrelevement> EmployePrelevements { get; set; }
        public virtual ICollection<EmployeSalaire> EmployeSalaires { get; set; }
        public virtual ICollection<MouvementSalaire> MouvementSalaires { get; set; }
    }
}
