//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePret
    {
        public TypePret()
        {
            this.Prets = new HashSet<Pret>();
            this.Compagnies = new HashSet<Compagnie>();
        }
    
        public int TypePretID { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Pret> Prets { get; set; }
        public virtual ICollection<Compagnie> Compagnies { get; set; }
    }
}
