//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePaiement
    {
        public TypePaiement()
        {
            this.CompagnieTypePaiements = new HashSet<CompagnieTypePaiement>();
            this.EmployeSalaires = new HashSet<EmployeSalaire>();
        }
    
        public int TypePaiementID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<CompagnieTypePaiement> CompagnieTypePaiements { get; set; }
        public virtual ICollection<EmployeSalaire> EmployeSalaires { get; set; }
    }
}
