//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAjustement
    {
        public TypeAjustement()
        {
            this.PayeAjustements = new HashSet<PayeAjustement>();
        }
    
        public int TypeAjustementID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<PayeAjustement> PayeAjustements { get; set; }
    }
}
