using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Profile;
using System.Web.Security;

namespace Payroll.Account
{
    // This class replaces the ProfileCommon Class that is no longer automatically generated by Visual Studio
    // from the content of the <properties> elements of the <profile> parent in Web.config
    public class UserProfile : ProfileBase
    {
        public static UserProfile GetUserProfile(string username)
        {
            return Create(username) as UserProfile;
        }
        public static UserProfile GetUserProfile()
        {
            return Create(Membership.GetUser().UserName) as UserProfile;
        }

        [SettingsAllowAnonymous(false)]
        public string Prenom
        {
            get { return base["Prenom"] as string; }
            set { base["Prenom"] = value; }
        }

        [SettingsAllowAnonymous(false)]
        public string Nom
        {
            get { return base["Nom"] as string; }
            set { base["Nom"] = value; }
        }

        [SettingsAllowAnonymous(false)]
        public int? CompagnieID
        {
            get { return base["CompagnieID"] as int?; }
            set { base["CompagnieID"] = value; }
        }

        [SettingsAllowAnonymous(false)]
        public string Compagnie
        {
            get { return base["Compagnie"] as string; }
            set { base["Compagnie"] = value; }
        }

        [SettingsAllowAnonymous(false)]
        public bool? MustChangePassword
        {
            get { return base["MustChangePassword"] as bool?; }
            set { base["MustChangePassword"] = value; }
        }
    }
}